- name: Configure Web Server
  hosts: web
  become: yes
  tasks:
    - name: Test Connection
      ping:

    - name: Install Nginx and Git
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nginx
        - git

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website files to Nginx web root
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ item }}"
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "website/*"
        
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted

